### ISSUE TITLE
Make "camera" follow player

### ISSUE THREAD

**Issue by towerofnix** [liam4/slw#1]
Just modifying `getDrawnPosition` and `let view(start/end)(x/y)` should do it.. this is what I was having trouble with earlier, though! :P

**Comment by bates64** [comment]
Should the camera be a class? (It'd allow us to move between different "active" cameras for cutscenes.)

``` js
class Camera {
  x: number
  y: number  

  constructor() {
    this.x = 0
    this.y = 0
  }
}

game.camera = new Camera
```

Also, Entities have their own drawing mechanisms, so something like [CanvasRenderingContext2D.translate](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/translate) would be bettter!
