### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by dekrain** [liam4/slw#25]
I'm reproduced steps in README.md, but after `gulp build` I can't run game ;(

**Comment by towerofnix** [comment]
Yeah, sorry.

To run the game, you'll want to get a server running in the game's directory, due to various issues. `python3 -m http.server` or `python2 -m SimpleHTTPServer' should work. Then open up the server in your web browser (probably`http://localhost:8000`) and the game _should_ work.

**Comment by dekrain** [comment]
But without using gulp, it works great without server.

**Comment by dekrain** [comment]
Maybe code downloaded from server is encoded AS DOWNLOADED FILE as LF, but gulp result in CRLF.

**Comment by towerofnix** [comment]
Maybe, but I'm pretty sure the browser deals with that automatically so it shouldn't be a big issue.

Are you getting an error in the terminal console or the browser console? Or is it something completely different that I'm not understanding?

**Comment by bates64** [comment]
> But without using gulp, it works great without server.

That would break fonts.

**Comment by dekrain** [comment]
@liam4 logs are on my pull request

**Comment by towerofnix** [comment]
I still don't get what line endings would have to do with this issue.

What _is_ the issue? "I can't run the game" is about as handy as "my car doesn't work" :P – is there an error in the web browser console? If so, could you copy and paste it here? Does it not do anything at all? Is `gulp` not working properly? (Again, if so, could you copy and paste gulp's logs here?)

(edit: sorry if I'm not being very clear.)

**Comment by bates64** [comment]
Building works fine for the rest of us, even on your PR, @dekrain.

**Comment by dekrain** [comment]
When I build original code, result is other than file downloaded from the server
