### ISSUE TITLE
Physics

### ISSUE THREAD

**Issue by towerofnix** [liam4/slw#3]
Kinda important
- [x] Floor collision
- [x] Wall collision
- [x] Ceiling collision

**Comment by an-OK-squirrel** [comment]
how should walls work? should walljumps be a thing

**Comment by towerofnix** [comment]
You probably shouldn't be able to walk through walls, generally. (Though P-switches, tower switches and whatever to replace walls blah blah yeah that would be cool)

Whether or not walljumps should be a thing is debatable but probably

**Comment by bates64** [comment]
> Whether or not walljumps should be a thing is debatable but probably

SMW doesn't have walljumps

**Comment by towerofnix** [comment]
I'm pretty sure NSMB does though.

**Comment by bates64** [comment]
Yup. But this is **super** ~~mario~~ **liam** **world**.
